# docker-compose.yml
version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
      - "6380:6379"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./src/gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - api

  api:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
    networks:
      - app-network
    depends_on:
      - redis

networks:
  app-network:
    driver: bridge