# docker-compose.yml
services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - API_SERVICE_KEY=${API_SERVICE_KEY}  # .env 파일에서 가져옴
    depends_on:
      - redis
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./src/gateway/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src/gateway/conf.d:/etc/nginx/conf.d:ro  # 추가 설정파일 디렉토리
    depends_on:
      - fastapi
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  redis_data:

networks:
  app-network:
    driver: bridge